# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Z:\Ashok\PuppetCreativeSuite\ui\buildPuppet_ui.ui'
#
# Created: Thu Mar 29 17:53:53 2018
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(434, 544)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.groupBox_jointInputs = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_jointInputs.setObjectName(_fromUtf8("groupBox_jointInputs"))
        self.gridLayout_inputs = QtGui.QGridLayout(self.groupBox_jointInputs)
        self.gridLayout_inputs.setSpacing(5)
        self.gridLayout_inputs.setContentsMargins(5, 30, 5, 5)
        self.gridLayout_inputs.setObjectName(_fromUtf8("gridLayout_inputs"))
        self.label_fitJoints = QtGui.QLabel(self.groupBox_jointInputs)
        self.label_fitJoints.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_fitJoints.setObjectName(_fromUtf8("label_fitJoints"))
        self.gridLayout_inputs.addWidget(self.label_fitJoints, 0, 0, 1, 1)
        self.comboBox_fitJoints = QtGui.QComboBox(self.groupBox_jointInputs)
        self.comboBox_fitJoints.setObjectName(_fromUtf8("comboBox_fitJoints"))
        self.comboBox_fitJoints.addItem(_fromUtf8(""))
        self.gridLayout_inputs.addWidget(self.comboBox_fitJoints, 0, 1, 1, 1)
        self.button_fitJoints = QtGui.QPushButton(self.groupBox_jointInputs)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_fitJoints.sizePolicy().hasHeightForWidth())
        self.button_fitJoints.setSizePolicy(sizePolicy)
        self.button_fitJoints.setObjectName(_fromUtf8("button_fitJoints"))
        self.gridLayout_inputs.addWidget(self.button_fitJoints, 0, 2, 1, 1)
        self.label_mirrorFitJoints = QtGui.QLabel(self.groupBox_jointInputs)
        self.label_mirrorFitJoints.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_mirrorFitJoints.setObjectName(_fromUtf8("label_mirrorFitJoints"))
        self.gridLayout_inputs.addWidget(self.label_mirrorFitJoints, 1, 0, 1, 1)
        self.button_mirrorFitJoints = QtGui.QPushButton(self.groupBox_jointInputs)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_mirrorFitJoints.sizePolicy().hasHeightForWidth())
        self.button_mirrorFitJoints.setSizePolicy(sizePolicy)
        self.button_mirrorFitJoints.setObjectName(_fromUtf8("button_mirrorFitJoints"))
        self.gridLayout_inputs.addWidget(self.button_mirrorFitJoints, 1, 1, 1, 1)
        self.button_labelToggle = QtGui.QPushButton(self.groupBox_jointInputs)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_labelToggle.sizePolicy().hasHeightForWidth())
        self.button_labelToggle.setSizePolicy(sizePolicy)
        self.button_labelToggle.setObjectName(_fromUtf8("button_labelToggle"))
        self.gridLayout_inputs.addWidget(self.button_labelToggle, 1, 2, 1, 1)
        self.label_twistJoints = QtGui.QLabel(self.groupBox_jointInputs)
        self.label_twistJoints.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_twistJoints.setObjectName(_fromUtf8("label_twistJoints"))
        self.gridLayout_inputs.addWidget(self.label_twistJoints, 2, 0, 1, 1)
        self.spinBox_twistJoints = QtGui.QSpinBox(self.groupBox_jointInputs)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_twistJoints.sizePolicy().hasHeightForWidth())
        self.spinBox_twistJoints.setSizePolicy(sizePolicy)
        self.spinBox_twistJoints.setObjectName(_fromUtf8("spinBox_twistJoints"))
        self.gridLayout_inputs.addWidget(self.spinBox_twistJoints, 2, 1, 1, 1)
        self.button_updateTwistJoints = QtGui.QPushButton(self.groupBox_jointInputs)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_updateTwistJoints.sizePolicy().hasHeightForWidth())
        self.button_updateTwistJoints.setSizePolicy(sizePolicy)
        self.button_updateTwistJoints.setObjectName(_fromUtf8("button_updateTwistJoints"))
        self.gridLayout_inputs.addWidget(self.button_updateTwistJoints, 2, 2, 1, 1)
        self.label_jointRadius = QtGui.QLabel(self.groupBox_jointInputs)
        self.label_jointRadius.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_jointRadius.setObjectName(_fromUtf8("label_jointRadius"))
        self.gridLayout_inputs.addWidget(self.label_jointRadius, 3, 0, 1, 1)
        self.spinBox_jointRadius = QtGui.QDoubleSpinBox(self.groupBox_jointInputs)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_jointRadius.sizePolicy().hasHeightForWidth())
        self.spinBox_jointRadius.setSizePolicy(sizePolicy)
        self.spinBox_jointRadius.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.spinBox_jointRadius.setObjectName(_fromUtf8("spinBox_jointRadius"))
        self.gridLayout_inputs.addWidget(self.spinBox_jointRadius, 3, 1, 1, 1)
        self.button_jointRadiusReset = QtGui.QPushButton(self.groupBox_jointInputs)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_jointRadiusReset.sizePolicy().hasHeightForWidth())
        self.button_jointRadiusReset.setSizePolicy(sizePolicy)
        self.button_jointRadiusReset.setObjectName(_fromUtf8("button_jointRadiusReset"))
        self.gridLayout_inputs.addWidget(self.button_jointRadiusReset, 3, 2, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_jointInputs)
        self.groupBox_controlInputs = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_controlInputs.setObjectName(_fromUtf8("groupBox_controlInputs"))
        self.gridLayout_controlInputs = QtGui.QGridLayout(self.groupBox_controlInputs)
        self.gridLayout_controlInputs.setSpacing(5)
        self.gridLayout_controlInputs.setContentsMargins(5, 30, 5, 5)
        self.gridLayout_controlInputs.setObjectName(_fromUtf8("gridLayout_controlInputs"))
        self.slider_centerControl = QtGui.QSlider(self.groupBox_controlInputs)
        self.slider_centerControl.setOrientation(QtCore.Qt.Horizontal)
        self.slider_centerControl.setObjectName(_fromUtf8("slider_centerControl"))
        self.gridLayout_controlInputs.addWidget(self.slider_centerControl, 3, 2, 1, 1)
        self.label_worldControl = QtGui.QLabel(self.groupBox_controlInputs)
        self.label_worldControl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_worldControl.setObjectName(_fromUtf8("label_worldControl"))
        self.gridLayout_controlInputs.addWidget(self.label_worldControl, 4, 0, 1, 1)
        self.button_worldControl = QtGui.QPushButton(self.groupBox_controlInputs)
        self.button_worldControl.setMinimumSize(QtCore.QSize(35, 0))
        self.button_worldControl.setMaximumSize(QtCore.QSize(35, 16777215))
        self.button_worldControl.setText(_fromUtf8(""))
        self.button_worldControl.setObjectName(_fromUtf8("button_worldControl"))
        self.gridLayout_controlInputs.addWidget(self.button_worldControl, 4, 1, 1, 1)
        self.label_rightControl = QtGui.QLabel(self.groupBox_controlInputs)
        self.label_rightControl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_rightControl.setObjectName(_fromUtf8("label_rightControl"))
        self.gridLayout_controlInputs.addWidget(self.label_rightControl, 2, 0, 1, 1)
        self.label_leftControl = QtGui.QLabel(self.groupBox_controlInputs)
        self.label_leftControl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_leftControl.setObjectName(_fromUtf8("label_leftControl"))
        self.gridLayout_controlInputs.addWidget(self.label_leftControl, 1, 0, 1, 1)
        self.button_leftControl = QtGui.QPushButton(self.groupBox_controlInputs)
        self.button_leftControl.setMinimumSize(QtCore.QSize(35, 0))
        self.button_leftControl.setMaximumSize(QtCore.QSize(35, 16777215))
        self.button_leftControl.setText(_fromUtf8(""))
        self.button_leftControl.setObjectName(_fromUtf8("button_leftControl"))
        self.gridLayout_controlInputs.addWidget(self.button_leftControl, 1, 1, 1, 1)
        self.slider_leftControl = QtGui.QSlider(self.groupBox_controlInputs)
        self.slider_leftControl.setOrientation(QtCore.Qt.Horizontal)
        self.slider_leftControl.setObjectName(_fromUtf8("slider_leftControl"))
        self.gridLayout_controlInputs.addWidget(self.slider_leftControl, 1, 2, 1, 1)
        self.slider_rightControl = QtGui.QSlider(self.groupBox_controlInputs)
        self.slider_rightControl.setOrientation(QtCore.Qt.Horizontal)
        self.slider_rightControl.setObjectName(_fromUtf8("slider_rightControl"))
        self.gridLayout_controlInputs.addWidget(self.slider_rightControl, 2, 2, 1, 1)
        self.label_centerControl = QtGui.QLabel(self.groupBox_controlInputs)
        self.label_centerControl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_centerControl.setObjectName(_fromUtf8("label_centerControl"))
        self.gridLayout_controlInputs.addWidget(self.label_centerControl, 3, 0, 1, 1)
        self.button_rightControl = QtGui.QPushButton(self.groupBox_controlInputs)
        self.button_rightControl.setMinimumSize(QtCore.QSize(35, 0))
        self.button_rightControl.setMaximumSize(QtCore.QSize(35, 16777215))
        self.button_rightControl.setText(_fromUtf8(""))
        self.button_rightControl.setObjectName(_fromUtf8("button_rightControl"))
        self.gridLayout_controlInputs.addWidget(self.button_rightControl, 2, 1, 1, 1)
        self.button_centerControl = QtGui.QPushButton(self.groupBox_controlInputs)
        self.button_centerControl.setMinimumSize(QtCore.QSize(35, 0))
        self.button_centerControl.setMaximumSize(QtCore.QSize(35, 16777215))
        self.button_centerControl.setText(_fromUtf8(""))
        self.button_centerControl.setObjectName(_fromUtf8("button_centerControl"))
        self.gridLayout_controlInputs.addWidget(self.button_centerControl, 3, 1, 1, 1)
        self.slider_worldControl = QtGui.QSlider(self.groupBox_controlInputs)
        self.slider_worldControl.setOrientation(QtCore.Qt.Horizontal)
        self.slider_worldControl.setObjectName(_fromUtf8("slider_worldControl"))
        self.gridLayout_controlInputs.addWidget(self.slider_worldControl, 4, 2, 1, 1)
        self.spinBox_controlScale = QtGui.QDoubleSpinBox(self.groupBox_controlInputs)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_controlScale.sizePolicy().hasHeightForWidth())
        self.spinBox_controlScale.setSizePolicy(sizePolicy)
        self.spinBox_controlScale.setButtonSymbols(QtGui.QAbstractSpinBox.UpDownArrows)
        self.spinBox_controlScale.setObjectName(_fromUtf8("spinBox_controlScale"))
        self.gridLayout_controlInputs.addWidget(self.spinBox_controlScale, 0, 2, 1, 1)
        self.label_controlScale = QtGui.QLabel(self.groupBox_controlInputs)
        self.label_controlScale.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_controlScale.setObjectName(_fromUtf8("label_controlScale"))
        self.gridLayout_controlInputs.addWidget(self.label_controlScale, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_controlInputs)
        self.groupBox_build = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_build.setObjectName(_fromUtf8("groupBox_build"))
        self.gridLayout_build = QtGui.QGridLayout(self.groupBox_build)
        self.gridLayout_build.setSpacing(5)
        self.gridLayout_build.setContentsMargins(5, 30, 5, 5)
        self.gridLayout_build.setObjectName(_fromUtf8("gridLayout_build"))
        self.button_build = QtGui.QPushButton(self.groupBox_build)
        self.button_build.setObjectName(_fromUtf8("button_build"))
        self.gridLayout_build.addWidget(self.button_build, 0, 0, 1, 1)
        self.button_reBuild = QtGui.QPushButton(self.groupBox_build)
        self.button_reBuild.setObjectName(_fromUtf8("button_reBuild"))
        self.gridLayout_build.addWidget(self.button_reBuild, 0, 1, 1, 1)
        self.progressBar = QtGui.QProgressBar(self.groupBox_build)
        self.progressBar.setMinimumSize(QtCore.QSize(0, 15))
        self.progressBar.setMaximumSize(QtCore.QSize(16777215, 15))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.gridLayout_build.addWidget(self.progressBar, 1, 0, 1, 2)
        self.verticalLayout_2.addWidget(self.groupBox_build)
        self.groupBox_support = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_support.setObjectName(_fromUtf8("groupBox_support"))
        self.verticalLayout_support = QtGui.QVBoxLayout(self.groupBox_support)
        self.verticalLayout_support.setSpacing(5)
        self.verticalLayout_support.setContentsMargins(5, 30, 5, 5)
        self.verticalLayout_support.setObjectName(_fromUtf8("verticalLayout_support"))
        self.label_support = QtGui.QLabel(self.groupBox_support)
        self.label_support.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_support.setObjectName(_fromUtf8("label_support"))
        self.verticalLayout_support.addWidget(self.label_support)
        self.verticalLayout_2.addWidget(self.groupBox_support)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.groupBox_jointInputs.setTitle(_translate("MainWindow", "Joint Inputs", None))
        self.label_fitJoints.setText(_translate("MainWindow", "Fit Joints", None))
        self.comboBox_fitJoints.setItemText(0, _translate("MainWindow", "Subin", "abcd"))
        self.button_fitJoints.setText(_translate("MainWindow", "Import", None))
        self.label_mirrorFitJoints.setText(_translate("MainWindow", "Mirror Fit Joints", None))
        self.button_mirrorFitJoints.setText(_translate("MainWindow", "Mirror Across YZ", None))
        self.button_labelToggle.setText(_translate("MainWindow", "Lable Toggle", None))
        self.label_twistJoints.setText(_translate("MainWindow", "Twist Joints", None))
        self.button_updateTwistJoints.setText(_translate("MainWindow", "Update Twist Joints", None))
        self.label_jointRadius.setText(_translate("MainWindow", "Joint Radius", None))
        self.button_jointRadiusReset.setText(_translate("MainWindow", "Reset", None))
        self.groupBox_controlInputs.setTitle(_translate("MainWindow", "Control Inputs", None))
        self.label_worldControl.setText(_translate("MainWindow", "World Controls", None))
        self.label_rightControl.setText(_translate("MainWindow", "Right Controls", None))
        self.label_leftControl.setText(_translate("MainWindow", "Left Controls", None))
        self.label_centerControl.setText(_translate("MainWindow", "Center Controls", None))
        self.label_controlScale.setText(_translate("MainWindow", "Control Global Scale", None))
        self.groupBox_build.setTitle(_translate("MainWindow", "Build", None))
        self.button_build.setText(_translate("MainWindow", "Build - Puppet", None))
        self.button_reBuild.setText(_translate("MainWindow", "Rebuild", None))
        self.groupBox_support.setTitle(_translate("MainWindow", "Support", None))
        self.label_support.setText(_translate("MainWindow", "Copyright 2017 Subin. Gopi - All Rights Reserved.\n"
"subing85@gmail.com", None))

